version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_room
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_room_data:/var/lib/postgresql/data

volumes:
  postgres_room_data:
